### ISSUE TITLE
the steps of running the program

### ISSUE THREAD

**Issue by fadysamir66** [ksasemada/Yobit-WebSocket#1]
Can you please record a video explaining the steps to run this program
or write the steps to run the program
so that we can use it correctly

**Comment by ksasemada** [comment]
1. Download [yobit.software.exe](https://github.com/ksasemada/Yobit-WebSocket/releases/download/v1.0.0/yobit.software.exe)
2. Download and install [Microsoft .NET Framework 4.7.2](https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/124d2afe5c8f67dfa910da5f9e3db9c1/ndp472-kb4054531-web.exe)
3. Run yobit.software.exe

**Comment by fadysamir66** [comment]
> is this trading program
> i mean is this trading bot
> and if its not trading bot do you have a trading bot for yobit

is this trading program
i mean is this trading bot
and if its not trading bot do you have a trading bot for yobit

**Comment by fadysamir66** [comment]
> 1. Download [yobit.software.exe](https://github.com/ksasemada/Yobit-WebSocket/releases/download/v1.0.0/yobit.software.exe)
> 2. Download and install [Microsoft .NET Framework 4.7.2](https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/124d2afe5c8f67dfa910da5f9e3db9c1/ndp472-kb4054531-web.exe)
> 3. Run yobit.software.exe

is this trading program
i mean is this trading bot
and if its not trading bot do you have a trading bot for yobit

**Comment by ksasemada** [comment]
No. I dont have trading bot.
